// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type Appointment struct {
	AppointmentID int64     `json:"appointment_id"`
	TrainingID    int64     `json:"training_id"`
	UserID        int64     `json:"user_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type Training struct {
	TrainingID  int64     `json:"training_id"`
	Place       string    `json:"place"`
	Type        string    `json:"type"`
	DateAndTime time.Time `json:"date_and_time"`
	Price       int64     `json:"price"`
	Trainer     string    `json:"trainer"`
}

type User struct {
	// chat_id from telegram
	UserID    int64     `json:"user_id"`
	FullName  string    `json:"full_name"`
	IsAdmin   bool      `json:"is_admin"`
	CreatedAt time.Time `json:"created_at"`
}
